import fs from 'node:fs';
import path from 'node:path';

const root = path.join(import.meta.dirname, '..');

const { version } = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')) as { version: string };

const content = `/*!
 * Copyright (c) 2026-present, Vanilagy and contributors
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

// This file is generated by scripts/write-version.ts. Do not edit manually.

export const VERSION = '${version}';

export const VERSIONED_NAME = \`Mediabunny v\${VERSION}\`;
`;

const filePath = path.join(root, 'src', 'version.ts');
if (!fs.existsSync(filePath) || fs.readFileSync(filePath, 'utf8') !== content) {
	fs.writeFileSync(filePath, content);
	console.log(`Wrote version ${version} to ${path.relative(root, filePath)}`);
}
